### ISSUE TITLE
[Events] Imported state abbreviation is getting mapped incorrectly

### ISSUE THREAD

**Issue by Swingline0** [JMAConsulting/biz.jmaconsulting.amga#16]
Here's the event address info in the legacy system (ID 701)
![image](https://cloud.githubusercontent.com/assets/1479206/5284225/e5bea60a-7ae0-11e4-9144-e0d7727f31df.png)

Here it is in Civi, the state abbreviation should map to 'Washington' instead of 'Western Australia'
![image](https://cloud.githubusercontent.com/assets/1479206/5284260/0ebb5008-7ae1-11e4-9883-6e3122fc9232.png)

**Comment by Swingline0** [comment]
@Edzelopez This is still an issue. An example program would be 3579 in the legacy system. While the program has both country and state assigned, the country field in the Civi location is not being populated.

**Comment by JoeMurray** [comment]
Edsel, please review the Country lookup for 3579 as there is likely a different spelling or something causing the trouble. Also, please run a query to find other entries where the country is present in legacy db but not in CiviCRM, and resolve the misspellings manually, consulting with Eran only if necessary. Thanks.

**Comment by Edzelopez** [comment]
Yes, there was an error since the legacy had USA instead of United States. I have revised the migration logic to handle such cases as well.

**Comment by Swingline0** [comment]
This looks good now! Awesome!
