### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by Swingline0** [JMAConsulting/biz.jmaconsulting.amga#31]
I'm adding a DB post hook that will add certificates to contacts when they pass courses. I'm applying this hook on both Create and Edit events of Participants. I'd like to go over how these certificates are represented in Civi and amongst the custom code in order to make sure that they are accessible once migrated.

Furthermore, I'm including some validation logic that requires `participant_id` be associated with each certificate record. Would this be possible in terms of how the certificates are stored in the legacy system?

**Comment by Edzelopez** [comment]
Hi @Swingline0 

I would like to get started on the second round of migration. Could you point me towards the new legacy database? I believe I was using an old one before which raised some concerns over the programs that were imported.

**Comment by Swingline0** [comment]
@Edzelopez This is looking like it's coming together nicely. One request,

Can you set `custom_292` to `valid` for all certificates? 

I set the default value for the field but I guess that is only applied when adding entries from the contact summary.

**Comment by Edzelopez** [comment]
Done (Y)

**Comment by Swingline0** [comment]
Perfect. Thanks!
