### ISSUE TITLE
[Membership] Conversion of memberships

### ISSUE THREAD

**Issue by Swingline0** [JMAConsulting/biz.jmaconsulting.amga#40]
This is a new request regarding something I recently cleared up with AMGA. As you've seen, there are a variety of memberships in the legacy system. The model AMGA is moving to consists of two memberships with an additional certification fee added based on the member's certification level. Since certifications are already being migrated, we need to ensure the memberships are handled correctly. I've summarized the requirements below, do you think this would be feasible to incorporate into the migration script?

Legacy Membership Types
---

- IFMGA via AMGA
- IFMGA via Reciprocal
- Associate Member
- Certified Guide
- Individual Member
- Student Associate Member
- Unclassified

New Types
---

- Professional
- Supporter

Conversion
---

| Legacy                                       | Condition                                                                 | Civi  |
|----------------------------------------------|---------------------------------------------------------------------------|--------------|
| IFMGA via AMGA                               | *                                                                         | Professional |
| IFMGA via Reciprocal                         | *                                                                         | Professional |
| Associate Member                             | Member has been enrolled in a program OR has *any* certification          | Professional |
| Associate Member                             | Member has not been enrolled in any program nor has any certification     | Supporter    |
| Certified Guide                              | *                                                                         | Professional |
| Individual Member & Student Associate Member | Member has been enrolled in a program OR works for an accredited business | Professional |
| Individual Member & Student Associate Member | Member has not been enrolled in a program                                 | Supporter    |

*Unclassified* memberships are from a past migration and don't really hold any value. This membership could essentially be dropped without a worry. If it's easier to leave it, however, then that's fine too.

Notes
---

Most importantly is probably the membership status and expiration date stuff. Migrated memberships will be scattered in terms of their individual lifecycles so it's important that this stays in tact...

What do you think?

**Comment by Edzelopez** [comment]
I have implemented the logic, just one question though. What would one consider as an accredited business? For now, I have just checked if the member has a current employer.

**Comment by Swingline0** [comment]
Hmm... that's a good question. I don't see anything to indicate employees of accredited businesses in the legacy system. I'll check with the client to see. For now, lets not worry about employers. I'll get back to you on that. 

Hopefully this clears up the others:

| Legacy                             | Civi                                                                             |
|------------------------------------|----------------------------------------------------------------------------------|
| Certified Single Pitch Instructor  | Professional                                                                     |
| Certified Climbing Wall Instructor | Professional                                                                     |
| Certified Top Rope Site Manager    | Professional                                                                     |
| Individual member                  | Professional (If member has NO event registrations or certifications, Supporter) |
| IFMGA                              | Professional                                                                     |
| Inactive                           | Professional (If member has NO event registrations or certifications, Supporter) |

**Comment by Edzelopez** [comment]
Yep, that clears things up. I've added support for them in the latest PR.

**Comment by Swingline0** [comment]
You da man!! :sunglasses:  :sunny: :fire:

**Comment by pradpnayak** [comment]
:)

**Comment by Edzelopez** [comment]
Hi @Swingline0 

Although this issue is closed, just touching base to see if you have any confirmation on the criteria for an accredited business.

**Comment by Swingline0** [comment]
Sorry, forgot about that :smile: 

The legacy system does not designate accredited businesses, I apologize for that being part of the req's here. Lets just disregard that whole OR component of the individual/student associate conversion.

If they've taken at least one program, then they should be converted to professional. Otherwise, supporter. 

Good catch, sorry about the back and forth on this one.
