### ISSUE TITLE
[Contacts] Use roles for group association

### ISSUE THREAD

**Issue by Swingline0** [JMAConsulting/biz.jmaconsulting.amga#46]
The legacy system uses roles to permit various functionality to parts of the system. We're employing a similar tactic except using Civi groups. In order to map functionality accordingly, I'm hoping you can add functionality to map legacy roles to civi groups. 

| Legacy        | Civi                         |
|---------------|------------------------------|
| Member        | Ignore                       |
| Administrator | Administrators (ID: 1)       |
| Provider      | Providers > General (ID: 53) |
| Instructor    | Instructor Team (ID: 17)     |

Is this feasible, @Edzelopez?

Thanks!

**Comment by Edzelopez** [comment]
Done in the latest PR

**Comment by Swingline0** [comment]
Awesome. Looks good! :+1:
