### ISSUE TITLE
[Events] A way to identify migrated events

### ISSUE THREAD

**Issue by Swingline0** [JMAConsulting/biz.jmaconsulting.amga#47]
Because migrated events are going to need to be represented differently in the student dashboard, I'll need a way to differentiate between events brought over from the legacy system and those created natively in Civi.

Is there anything like this already or would this require a custom field?

**Comment by Edzelopez** [comment]
Hi @Swingline0 

Yes we did have a great holiday break, hope you did too!

I've added support for the boolean field in the migration logic.

**Comment by Swingline0** [comment]
Thanks!
