### ISSUE TITLE
Additional Field Mappings for Provider Programs

### ISSUE THREAD

**Issue by Swingline0** [JMAConsulting/biz.jmaconsulting.amga#52]
| Legacy Field                  | Civi                                                                                                        |
|-------------------------------|-------------------------------------------------------------------------------------------------------------|
| program[provider_name_line_1] | custom_181                                                                                                  |
| program[member_id]            | custom_130 (Will need to populated with Civi contact ID, matched from the External ID of the legacy system) |

**Comment by Edzelopez** [comment]
Added both the mappings.

**Comment by Swingline0** [comment]
@Edzelopez @pradpnayak @JoeMurray It doesn't look like the `custom_130` field has been populated on any of the events in the final migration. Looking at the revision to handle this (06c8cb6ad48751f301fa9c61fa968177270c7cf1) it looks fairly clean-- I'm not sure why it wouldn't work. 

Is there anything that can be done about this in order to resolve the issue retroactively? This presents an issue where some 2000 programs would need to be updated tediously by hand.

**Comment by Swingline0** [comment]
If I had to guess, I'd figure that the field isn't getting set as this seems to be bug with the API... retrieving programs by a contact reference custom field doesn't work either. 

In the interest of keeping things on schedule, I'll go ahead and put something together to fill in the missing data here. Thanks for everything guys!

**Comment by pradpnayak** [comment]
The reason for this is there are 2 'PROVIDER' constants defined in 2 different files
https://github.com/JMAConsulting/biz.jmaconsulting.amga/blob/master/api/v3/Job/CreateEvents.php#L7
https://github.com/Swingline0/AMGA/blob/master/wp-content/plugins/amga-provider-dashboard/provider-dashboard.php#L3

So the event api params was build $param[145] = 1234;
rather $param['custom_130'] =1234;

**Comment by pradpnayak** [comment]
The Query below will update all the event with there provider.

UPDATE 
`civicrm_value_program_status_18` cu
INNER JOIN civicrm_event e ON e.id = cu.entity_id
LEFT JOIN amga_legacy_1.programs l ON l.program_code = e.title
LEFT JOIN civicrm_contact co ON co.external_identifier = l.member_id
SET cu.provider_130 = co.id
WHERE provider_130 IS NULL AND l.member_id IS NOT NULL AND l.provider = 'Provider';

Note: amga legacy mysql db(latest) should be present on the same server and mysql user should have access to it.

**Comment by Swingline0** [comment]
Not sure why the two constants came up but a number of provider fields were
added over the time of testing the migration script.

I prepared a quick query and script to patch in the missing data. I
appreciate your providing this query as well though. All in all, fine work!

Thanks!
