### ISSUE TITLE
[Participants] Participant Status Mapping

### ISSUE THREAD

**Issue by Swingline0** [JMAConsulting/biz.jmaconsulting.amga#53]
AMGA has brought to my attention that some of the participant statuses aren't getting mapped correctly. Additionally, they've request a few others be added which I've included below.

| Legacy Value             | Civi Value |
|--------------------------|------------|
| 2 (Wait List)            | 7          |
| 12 (Under Review)        | 35         |
|  103 (Incomplete Resume) | 34         |

**Comment by Edzelopez** [comment]
Hi @Swingline0,

Could you please provide some examples of incorrectly mapped statuses so I can have a look?
I have added the 3 statuses to the migration script.

**Comment by Edzelopez** [comment]
As per the mail, this should be resolved during the next migration.

**Comment by Swingline0** [comment]
Looks good here too. Nice!
